# Generated by Django 6.0.6 on 2026-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(db_column='Student_Id', primary_key=True, serialize=False)),
                ('roll_no', models.CharField(db_column='RollNo', max_length=50, unique=True)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('major', models.CharField(db_column='Major', max_length=100)),
            ],
            options={
                'db_table': 'Tbl_Student',
            },
        ),
    ]
